### ISSUE TITLE
SqlAGReplica: 'ReadOnlyRoutingList' is a ReadOnly property

### ISSUE THREAD

**Issue by Zuldan** [PowerShell/SqlServerDsc#518] opened 2017-04-20 11:21 UTC
**Details of the scenario you try and problem that is occurring:**

If I change a setting on a replica (bringing it out of desired state), for example FailoverMode then I receive "'ReadOnlyRoutingList' is a ReadOnly property" when performing a consistency check.

```
VERBOSE: [LABSERVER02]: LCM:  [ End    Resource ]  [[xWaitForAvailabilityGroup]WaitForAvailabilityGroupMyLab]
VERBOSE: [LABSERVER02]: LCM:  [ Start  Resource ]  [[xSQLServerAlwaysOnAvailabilityGroupReplica]SQLAOGroupMyLabReplica]
VERBOSE: [LABSERVER02]: LCM:  [ Start  Test     ]  [[xSQLServerAlwaysOnAvailabilityGroupReplica]SQLAOGroupMyLabReplica]
VERBOSE: [LABSERVER02]:                            [[xSQLServerAlwaysOnAvailabilityGroupReplica]SQLAOGroupMyLabReplica] 2017-04-20_21-12-30: Connected to SQL LABSERVER02
VERBOSE: [LABSERVER02]:                            [[xSQLServerAlwaysOnAvailabilityGroupReplica]SQLAOGroupMyLabReplica] 2017-04-20_21-12-30: 'FailoverMode' should be 'Manual' but is 'Automatic'
VERBOSE: [LABSERVER02]: LCM:  [ End    Test     ]  [[xSQLServerAlwaysOnAvailabilityGroupReplica]SQLAOGroupMyLabReplica]  in 0.5160 seconds.
VERBOSE: [LABSERVER02]: LCM:  [ Start  Set      ]  [[xSQLServerAlwaysOnAvailabilityGroupReplica]SQLAOGroupMyLabReplica]
VERBOSE: [LABSERVER02]:                            [[xSQLServerAlwaysOnAvailabilityGroupReplica]SQLAOGroupMyLabReplica] 2017-04-20_21-12-30: Preferred module SqlServer found.
VERBOSE: [LABSERVER02]:                            [[xSQLServerAlwaysOnAvailabilityGroupReplica]SQLAOGroupMyLabReplica] 2017-04-20_21-12-30: Importing SqlServer module.
VERBOSE: [LABSERVER02]:                            [[xSQLServerAlwaysOnAvailabilityGroupReplica]SQLAOGroupMyLabReplica] 2017-04-20_21-12-30: Connected to SQL LABSERVER02
VERBOSE: [LABSERVER02]:                            [[xSQLServerAlwaysOnAvailabilityGroupReplica]SQLAOGroupMyLabReplica] 2017-04-20_21-12-30: Connected to SQL LABSERVER01
VERBOSE: [LABSERVER02]:                            [[xSQLServerAlwaysOnAvailabilityGroupReplica]SQLAOGroupMyLabReplica] 2017-04-20_21-12-30: Getting the effective permissions for the login 'NT SERVICE\ClusSvc' on 'MSSQLSERVER'.
VERBOSE: [LABSERVER02]:                            [[xSQLServerAlwaysOnAvailabilityGroupReplica]SQLAOGroupMyLabReplica] 2017-04-20_21-12-30: Connected to SQL LABSERVER02
Invoke-CimMethod : 'ReadOnlyRoutingList' is a ReadOnly property.
At C:\Lab\SQLAOAG.ps1:20 char:5
+     Invoke-CimMethod -CimSession $ServerName -Name PerformRequiredCon ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-CimMethod], CimException
    + FullyQualifiedErrorId : PropertyAssignmentException,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand
    + PSComputerName        : LABSERVER02
```

**The DSC configuration that is using the resource (as detailed as possible):**

```
xSQLServerAlwaysOnAvailabilityGroupReplica "SQLAOGroup$($AG)Replica"
{
    DependsOn                     = "[xWaitForAvailabilityGroup]WaitForAvailabilityGroup$AG"
    Ensure                        = 'Present'
    PsDscRunAsCredential          = $Credential
    Name                          = $Node.NodeName
    AvailabilityGroupName         = $AG
    SQLServer                     = $Node.NodeName
    SQLInstanceName               = $Node.SQLInstanceName
    AvailabilityMode              = 'SynchronousCommit'
    ConnectionModeInPrimaryRole   = 'AllowAllConnections'
    FailoverMode                  = 'Manual'
    PrimaryReplicaSQLServer       = $AGClusterData.PrimaryAG
    PrimaryReplicaSQLInstanceName = $Node.SQLInstanceName
}
```
**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**

Server: Windows 2012 R2 (Update)
SQL Server: 2016 SP1 CU2
Powershell: 5.1

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**

SqlServer v20.0

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

7.0.0.0

**Comment by Zuldan** [comment] 2017-06-08 18:56
I think I found the root cause. The error only appears if the config on the node changes and it's not the primary. Config for the AOAG can only be changed on a node if the node is primary (Microsoft has set this requirement). 

So to replicate this you would:

1. On Node01 (Primary) make a change.
2. Failover the AOAG to Node02 (Secondary)
3. On Node01 (Secondary) perform a consistency check

So I guess we could either say this is by design or the DSC resource should only connect to the Primary node when making changes. What are everyone's thoughts?

**Comment by johlju** [comment] 2017-06-09 18:16
I agree. But it looks like the resource do connect to the Primary replica. If it is not the primary replica, it connect to the primary replica. But it seems there is a problem somewhere here. https://github.com/PowerShell/xSQLServer/blob/dev/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica.psm1#L241

But this should be easier to look into when you provided the steps to reproduce the behaviour.

**Comment by aalmeida89** [comment] 2018-03-06 20:19
Hello guys, I am having the same problem, but not only on the secondary, but the primary too.
You resolved it ?

DSC configuration:
SqlAGReplica AddReplica 
        {
            Ensure                       = "Present" 
            Name                         = $Node.NodeName + "\" + $Node.InstanceName
            AvailabilityGroupName        = $Node.AGName
            ServerName                   = $Node.NodeName
            InstanceName                 = $Node.InstanceName
            PrimaryReplicaServerName   = ( $AllNodes | Where-Object { $_.Role -eq 'Primary' } ).NodeName
            PrimaryReplicaInstanceName = ( $AllNodes | Where-Object { $_.Role -eq 'Primary' } ).InstanceName 
            ReadOnlyRoutingConnectionUrl = 'TCP://' + $Node.NodeName + "." + $ENV:USERDNSDOMAIN + ":31244"
            #ReadOnlyRoutingList          = 'SQLDsc-2\SQLCore2016'
            AvailabilityMode              = 'SynchronousCommit'
            ConnectionModeInPrimaryRole   = 'AllowAllConnections'
            ConnectionModeInSecondaryRole = 'AllowAllConnections'
            FailoverMode                  = 'Manual'
            PsDscRunAsCredential = $domainSetup
        }

ERROR:
'ReadOnlyRoutingList' is a ReadOnly property.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : PropertyAssignmentException
    + PSComputerName        : SQLDsc-1
'ReadOnlyRoutingList' is a ReadOnly property.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : PropertyAssignmentException
    + PSComputerName        : SQLDsc-2

Server: Windows 2016
SQL Server: 2016 SP1 CU2
Powershell: 5.1
SQLServerDSC: dev (11.0)

**Comment by johlju** [comment] 2018-03-07 16:53
The each node should connect to the Primary according to this code.

https://github.com/PowerShell/SqlServerDsc/blob/29f2fc48f65fdf44d7e98a11dc0bf78de07db4a0/DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1#L250-L260

And here it

**Comment by johlju** [comment] 2018-03-07 16:58
@aalmeida89 The node that is assigned to `Name` in the above configuration is it your secondary replica?

The target node should connect to the Primary according to this code.

https://github.com/PowerShell/SqlServerDsc/blob/29f2fc48f65fdf44d7e98a11dc0bf78de07db4a0/DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1#L250-L260

And here it will get the replica (that is assigned to `Name`).

https://github.com/PowerShell/SqlServerDsc/blob/29f2fc48f65fdf44d7e98a11dc0bf78de07db4a0/DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1#L306-L311

And here it will set the routing list. I wonder if it will go out to the secondary and try to update it, but it is not allowed becuase it is not running under the primary role. Is it that this setting can only be set when the replica is running under the primary role?

https://github.com/PowerShell/SqlServerDsc/blob/29f2fc48f65fdf44d7e98a11dc0bf78de07db4a0/DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1#L374-L378

**Comment by johlju** [comment] 2018-03-07 17:22
> A given read-only routing list takes effect only when the local replica is running under the primary role. **This list must be specified on a replica-by-replica basis, as needed.**
>[What Replica Properties Do you Need to Configure to Support Read-Only Routing?](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-read-only-routing-for-an-availability-group-sql-server#RORReplicaProperties)

So I assume the bold text above *'must be specified on a replica-by-replica basis, as needed'* is meaning that this needs to be set on each replica, 

>You must be connected to the server instance that hosts the current primary replica.
>[Prerequisites](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-read-only-routing-for-an-availability-group-sql-server#Prerequisites)

And that says, to set this you must be connected to the primary replica. I suppose this means that to be able to set this, the "secondary" must (can) only be configured once it starts to run under the primary role.

Can someone confirm this?

**Comment by codykonior** [comment] 2018-10-18 10:01
You modify it on the primary replica.

But you can change it for every replica on the primary replica, whether it's currently primary or secondary.

**Closed** 2019-03-10 11:49 UTC
Labels: bug, help wanted
