### ISSUE TITLE
Error when using in DSC Pull server

### ISSUE THREAD

**Issue by MethosNL** [PowerShell/SqlServerDsc#413] opened 2017-02-28 09:10 UTC
EventID: 4104
Source: Desired State Configuration
Level: Error
ErrorId: 0x1
ErrorDetail: The PowerShell DSC resource C:\Program Files\WindowsPowerShell\Modules\xSQLServer\DscResources\MSFT_xSQLServerDatabase does not contain the corresponding MOF file C:\Program Files\WindowsPowerShell\Modules\xSQLServer\DscResources\MSFT_xSQLServerDatabase\MSFT_xSQLServerDatabase.schema.mof

**DSC config used:**

configuration BlahBlah
{
    Import-DscResource –ModuleName "xSQLServer" -ModuleVersion 5.0.0.0
    node $AllNodes.NodeName
    {
        xSQLServerDatabase Database
        {
            Ensure = 'Present'
            Name = 'BlahBlah'
            SQLServer = $Node.NodeName
            SQLInstanceName = "MSSQLSERVER"
        }
    }
}

PS Version Pull server: 5.1.14393.693 (WS2016)
PS Version target: 4.0 (w2k12R2)

**Comment by johlju** [comment] 2017-02-28 12:36
Does the mof file exist in the path `C:\Program Files\WindowsPowerShell\Modules\xSQLServer\DscResources\MSFT_xSQLServerDatabase\MSFT_xSQLServerDatabase.schema.mof`?
Does it only happen for the resource xSQLServerDatabase? Other resources in xSQLServer are working?

**Comment by MethosNL** [comment] 2017-02-28 12:38
The MOF file does exist, all other resources also have a MOF file.
Haven't checked other resources since our deployment starts with a database, so haven't gotten to any other resources from the module yet ;-)

**Comment by johlju** [comment] 2017-02-28 12:41
Ah, I understand. :) Would it be possible for you to add a dummy login with xSQLServerLogin maybe? Just to verify. 
If that works then there is something wrong with that particular resource; xSQLServerDatabase.

**Comment by MethosNL** [comment] 2017-02-28 12:50
xSQLServerLogin works like a charm :-)

**Comment by johlju** [comment] 2017-02-28 17:57
Hmm... It should not be a problem with the resource then. It is something else.

If you run the below cmdlet on the target node, does it return the resource?

```
Get-DSCResource -Name xSQLServerDatabase
```

If it return the resource successfully, is it possible for you to run the configuration with `Start-DscConfiguration` (push mode)? So we can see if this is a problem when running from the pull server.

**Comment by MethosNL** [comment] 2017-03-01 13:46
Well, no. That's the whole point.
The error that's given in the eventvwr means that due to the fact that the xsqlserver module doens't comply to what the system expects, it can't pull the module down from the pull server.

**Comment by johlju** [comment] 2017-03-01 18:19
A few question before I try to reproduce this.

1. Does it do pull down other modules, but just not xSQLServer?
1. When you said the .mof file did exist in the folder `C:\Program Files\WindowsPowerShell\Modules\xSQLServer\DscResources\MSFT_xSQLServerDatabase\MSFT_xSQLServerDatabase.schema.mof`, did you mean that `MSFT_xSQLServerDatabase.schema.mof` did exist in the zip archive you put in the module path?
1. Did you prepare the archive as mention here [DSC resource module package format](https://msdn.microsoft.com/en-us/powershell/dsc/pullserver#dsc-resource-module-package-format)?

Trying to reproduce this might take me a while since I have to set up a pull server in my lab.

**Comment by luigilink** [comment] 2017-03-01 19:34
@johlju I have a pull server already configured in my lab, I can help on this issue.

My turn, I have one question 😄 
Why powershell versions are different between targets and pull server ?
The PS 4.0 can be used with PSRunAsCredential, so how can it be possible to connect to SQL with the default local account used by DSC ?

**Comment by MethosNL** [comment] 2017-03-15 08:05
Good point about the different versions of PS.
I've talked with the customer and we decided to test WMF5 on it and see if the application would still work... and it did :-)

Yet, we decided not to go with pull server, and use push through a CD pipeline for deployment. Therefore, the problem may still exist but it doesn't bother us anymore...
On to the next project :-) Thanks!

**Comment by johlju** [comment] 2018-01-05 11:34
Closing this as nobody else has reported the problem, and the issue submitter can not help to reproduce the error. If someone else do have this problem, then please comment on the closed issue and we repopen the issue.

**Closed by johlju** 2018-01-05 11:34 UTC
Labels: question
