### ISSUE TITLE
Error on AvailabilityGroup Creation: SqlAG

### ISSUE THREAD

**Issue by mohamednazar** [PowerShell/SqlServerDsc#1151] opened 2018-06-25 15:53 UTC
#### Details of the scenario you tried and the problem that is occurring

When Trying to create Sql Availability Group I am getting error.

Generated at 2018-06-25 15:42:49 +0000
```
Chef::Exceptions::PowershellCmdletException: dsc_resource[create_availability_group] (SqlServer::ae-dsc-availability-group line 11) had an error: 
Chef::Exceptions::PowershellCmdletException: Powershell Cmdlet failed: 
PowerShell DSC resource MSFT_SqlAG  failed to execute Set-TargetResource functionality with error message: 
Creating the availability group 'AG_DBTL'. 
InnerException: Cannot bind parameter 'InputObject'. Cannot convert the "[DBServer01]" value of type "Microsoft.SqlServer.Management.Smo.Server" to type "Microsoft.SqlServer.Management.Smo.Server". 
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```
#### The DSC configuration that is using the resource (as detailed as possible)
```
dsc_resource 'create_availability_group' do
  resource :SqlAG
  property :Name, 'AG_DB01'
  property :Ensure, 'Present'
  property :InstanceName, 'MSSQLSERVER'
  property :ServerName, 'localhost'
  property :AutomatedBackupPreference, 'Primary'
  property :AvailabilityMode, 'SynchronousCommit'
  property :ConnectionModeInPrimaryRole, 'AllowAllConnections'
  property :FailoverMode, 'Automatic'
  property :PsDscRunAsCredential, ps_credential((node['sqlserver']['Username']), (node['sqlserver']['Password']))
end
```

#### Version of the operating system and PowerShell the target node is running

Caption                                  OSArchitecture Version    MUILanguages $PSVersionTable.PSVersion
-------                                  -------------- -------    ------------ -------------------------
Microsoft Windows Server 2016 Datacenter 64-bit         10.0.14393 {en-US}      5.1.14393.2248

#### SQL Server edition and version the target node is running

Edition  : Enterprise Edition: Core-based Licensing
Version  : 13.2.5026.0
Language : 1033

#### What SQL Server PowerShell modules, and which version, are present on the target node.

Name       Version Path
----       ------- ----
xSQLServer 9.1.0.0 C:\Program Files\WindowsPowerShell\Modules\xSQLServer\9.1.0.0\xSQLServer.psd1
SQLPS      1.0     C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch

Name         Version  Path
----         -------  ----
SqlServerDsc 11.3.0.0 C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\11.3.0.0\SqlServerDsc.psd1

**Comment by mohamednazar** [comment] 2018-06-25 16:36
I have removed xSqlServer DSC Resource and now my server has only SqlServerDsc resource only.

see the output of get-Module *sql* -ListAvailable

PS C:\Users> Get-Module *sql* -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   11.3.0.0   SqlServerDsc


    Directory: C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.0        SQLPS                               {Backup-SqlDatabase, Save-SqlMigrationReport, Add-SqlAvail...

**Comment by johlju** [comment] 2018-06-26 07:05
Please see issue #812, I think you experience the same problem.

**Comment by mohamednazar** [comment] 2018-06-26 10:12
Yes same problem but only one change. #812 facing issue with xSqlServer DSCResource but in my case I am facing issue with SqlServerDsc DSCResource. Also I dont find any solution provided for #812, so please let me know how do I resolve this issue?

Thanks

**Comment by johlju** [comment] 2018-06-26 10:46
@mohamednazar Issue #812 is for SqlServerDsc as well, just that the issue has been open since before the rename. 
Do you have SSMS installed on the target node?
Do you have any other instances of SQL server than version 13? 
Are you running SQL Server 2016 with Service Pack 2 (just to confirm the version number)?

**Comment by mohamednazar** [comment] 2018-06-26 10:59
@johlju 

we installed with SSMS 17.7 on target node.
There are only one version (13.0.5149.0) of Sql server is running on target node.
Target node installed with SQL Server 2016 with Service pack 2 and Cumulative Update 1

Microsoft SQL Server 2016 (SP2-CU1) (KB4135048) - 13.0.5149.0 (X64)   May 19 2018 09:41:57   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 


Please let me know if you need any other info?

Thanks,

**Comment by mohamednazar** [comment] 2018-06-27 11:31
@johlju  waiting for your response.

**Comment by johlju** [comment] 2018-06-27 13:16
I running this in my lab to see if I can reproduce it, but it's gonna take a while since I don't have that much bandwidth for this.

**Comment by mohamednazar** [comment] 2018-06-27 13:18
Thanks for the update, please let me know as soon as you find anything...

**Comment by johlju** [comment] 2018-06-27 15:57
The problem seems to be when SSMS is installed prior to the configuration is run. SSMS probably adds assemblies that are the wrong version than SQLPS expects.

```
PowerShell DSC resource MSFT_SqlAG  failed to execute Set-TargetResource functionality with error message: Creating the availability group 'TESTCLU02-AG1'. InnerException: Cannot bind parameter 'InputObject'. Cannot convert the "[sqltest.company.local\SQL2016]" value of type "Microsoft.SqlServer.Management.Smo.Server" to type "Microsoft.SqlServer.Management.Smo.Server".
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
```

When running the configuration without SSMS 17.7 installed the AG is created successfully.

**Comment by mohamednazar** [comment] 2018-06-27 18:49
Thanks after I removed SSMS 17.7 I am able to create SQLAG using DSCResource. 

I have to install SSMS before SQLAG creation, so shall I install any lower version of SSMS like 14.0.17177.0?

**Comment by johlju** [comment] 2018-06-28 08:15
Not sure it helps with a lower version, but please try and let me know the result. An workaround is to install SSMS after AG is created, but then maybe consistency checks fail when SSMS is installed -  I have not tested that. 🤔 

The problem I think is that "Import-Module SQLPS" is loading the wrong assemblies when SSMS is installed.

**Comment by johlju** [comment] 2018-06-28 09:44
Using SSMS 17.8.1 together with latest SqlServer module seems to work.

**Successful**
* Windows Server 2012 R2
* SSMS 17.8.1
* Latest SqlServer module
* SQL Server 2016 SP2 CU1
* Run SqlAG configuration

**Comment by johlju** [comment] 2018-06-28 09:53
@mohamednazar can you confirm that the SSMS 17.8.1 and latest SqlServer module works for you as well?

**Comment by mohamednazar** [comment] 2018-06-28 09:55
upgrading ssms to 17.8.1, how to I get latest SqlServer module? Shall I uninstall and reinstall SqlServerDsc module? While I reinstalling will it get latest version of module?

**Comment by johlju** [comment] 2018-06-28 09:58
SqlServer module and SqlServerDsc module is two different modules. SqlServer is the "new" SQLPS module. https://www.powershellgallery.com/packages/SqlServer

**Comment by mohamednazar** [comment] 2018-06-28 10:01
Oh. I am using SqlServerDsc module. Shall I continue to use it or should I change to SqlServer? Which one is the correct one?

**Comment by johlju** [comment] 2018-06-28 10:03
Ah sorry, you should have both installed on the target node 🙂 SqlServerDsc have the DSC resources, and SqlServer has all the cmdlets that SQLPS have.

**Comment by mohamednazar** [comment] 2018-06-28 10:06
ok I will install both and try with 17.8 version of SSMS. I will update you the status once done.

**Comment by johlju** [comment] 2018-07-09 06:54
@mohamednazar I have merged a few PR that will mitigate these issue (loading wrong assembly) in certain scenarios. But you combination of using SQLPS module with SSMS 17.x will never work. Closing this, and assuming you got this resolved when using the necessary versions of each components above.

**Closed by johlju** 2018-07-09 06:54 UTC
Labels: needs more information

**Comment by mohamednazar** [comment] 2018-07-09 09:56
@johlju  installing SQL AG first then SSMS 17.x is working fine for me. You can close this case.
