### ISSUE TITLE
SqlSetup: SQLSvcAccount credentials does not work after a reboot

### ISSUE THREAD

**Issue by hansmelin** [PowerShell/SqlServerDsc#376] opened 2017-02-09 11:53 UTC
**Details of the scenario you try and problem that is occurring:**
When I set SQLSvcAccount and run xSQLServerSetup everything works fine and sql server is installed and the correct account is set for the sql server service.

But when I reboot the machine, none of the sql services will start. And I can't start it from services UI either.

The only way is to set the password for the sql service again and click ok. And also set a blank password for the sql agent service and click ok. Then I can start the services.

When I have done this manually it works to reboot the server. 

But If I run the DSC once more and reboot I have to do the procedure above again to be able to start the services.

I have only tested with creating credentials with clear text password and have not yet setup a certificate store. But it should work anyhow.

**The DSC configuration that is using the resource (as detailed as possible):**
```
        xSQLServerSetup SqlServerSetup
        {      
            SourcePath = $ConfigurationData.SoftwarePath + "sql_server_2016"                     
            InstanceName = "MSSQLSERVER"
            Features = "SQLEngine,FullText,RS,AS,IS"
            SetupCredential = new-object -typename System.Management.Automation.PSCredential -argumentlist ($ConfigurationData.InstallerCredential.User, (ConvertTo-SecureString -String $ConfigurationData.InstallerCredential.Password -AsPlainText -Force))
            SourceCredential = new-object -typename System.Management.Automation.PSCredential -argumentlist ($ConfigurationData.InstallerCredential.User, (ConvertTo-SecureString -String $ConfigurationData.InstallerCredential.Password -AsPlainText -Force))
            SQLSvcAccount  = new-object -typename System.Management.Automation.PSCredential -argumentlist ($ConfigurationData.SqlSQLSvcAccountCredential.User, (ConvertTo-SecureString -String $ConfigurationData.SqlSQLSvcAccountCredential.Password -AsPlainText -Force))
            SecurityMode = "SQL"
            SAPwd = new-object -typename System.Management.Automation.PSCredential -argumentlist ("sa", (ConvertTo-SecureString -String $ConfigurationData.SqlSAPassword -AsPlainText -Force))
            SQLCollation = "Finnish_Swedish_CI_AS"
            SQLUserDBDir = "D:\data\"
            SQLUserDBLogDir = "L:\data\"
            SQLTempDBDir = "T:\data\"
            DependsOn = "[WindowsFeature]NETFramework45Core"
        }
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows 2016 Server UI

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

**Comment by johlju** [comment] 2017-02-09 20:51
That is strange, I will look into this. The `$ConfigurationData.InstallerCredential` you are referencing in the configuration. Is that a Credential object or a another typ of object?

**Comment by hansmelin** [comment] 2017-02-10 08:52
No, it's just a custom object holding a username and a password. I'm still in the testing phase of the configuration and I create the credentials with clear text passwords for now. I haven't had the time to setup the certficate store yet.

`$ConfigurationData.SqlSQLSvcAccountCredential.User` => user name in clear text
`$ConfigurationData.SqlSQLSvcAccountCredential.Password` => password in clear text

**Comment by johlju** [comment] 2018-01-05 11:31
@hansmelin Did you still have this problem? I can't reproduce it.

**Comment by hansmelin** [comment] 2018-01-08 07:55
We don't use DSC for our SQL Servers anymore. So I don't know if this is an issue anymore.

**Comment by johlju** [comment] 2018-01-08 14:00
@hansmelin thanks for responding! I'm closing this issue since I cant reproduce the problem. If someone else encounters this problem, comment on this issue and we reopen the issue.

**Closed by johlju** 2018-01-08 14:00 UTC
Labels: question
