### ISSUE TITLE
The resource SqlSetup resource does not show in Azure Automation

### ISSUE THREAD

**Issue by dead8171** [PowerShell/SqlServerDsc#913] opened 2017-11-22 07:54 UTC
I found this very weird that I cant see the xSQLserversetup module in the Azure automation account, this module is required so that I can install the SQL Server instance onto the node, but since I cant see this configuration inside the xSQLserver module, how can I use this module, I tried importing this but it didnt got imported as well, Is anyone having this kind of issue??

Please How can I use the module for the installation of the module, or tell me how can I run the script so that I generate the .mof file locally and then install this onto my machine.

**Comment by randomnote1** [comment] 2017-11-22 12:07
Hi @dead8171, this is a known bug that is in the process of being resolved in PR #851. See the following issues for some more details:

- #310
- #705
- #713 
- #716

The known workarounds are listed [here](https://github.com/PowerShell/xSQLServer/issues/716#issuecomment-323056385).

**Comment by dead8171** [comment] 2017-11-22 13:13
The workaround for this is use the xSQLserver 7.1.0.0 module, I have imported this but couldnt able to see the xSqlserversetup module in there please let me know about this, also How can I run the script locally, I mean I have to pass the credentials in the DSC to make it to work but I dont know how to do that.

**Comment by randomnote1** [comment] 2017-11-22 13:56
I want to make sure we're using the same terminology here. xSQLServerSetup is a DSC resource that is a part of the xSQLServer module. Can you see the xSQLServerSetup resource when you execute `Get-DscResource -Module xSQLServer -Name xSQLServerSetup`?

**Comment by dead8171** [comment] 2017-11-22 18:19
@randomnote1 Where should I execute this command since I am using Powershell of automation account. I know thats the part of the xSQLServer module but I cant seem to find that module in the Automation Account Powershell gallery.

**Comment by randomnote1** [comment] 2017-11-22 18:43
You should be able to navigate to the module version you wish to deploy in the [PowerShell Gallery](https://www.powershellgallery.com/packages/xSQLServer/7.1.0.0) and click the "Deploy to Azure Automation" button. From my limited testing, it will walk you through the steps to download the module into your automation account.

**Comment by raxso1** [comment] 2017-11-22 20:48
Hi 

@johlju and @randomnote1 
I am still having issue with xSQLSetup resource being loaded in AA account, I have followed the work around of deleting xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership, and zipping up the file. it loads successfully into AA, however I still cannot see the xSQLSetup resource, tried version 7.1.0.0, 8.0.0.0 and 9.0.0.0. Is there a fix?

**Comment by dead8171** [comment] 2017-11-23 06:52
@randomnote1 I have tried that, and it did deploy to the Automation Account, but I still cant see the xSQLServerSetup module inside the Automation Account, I have screenshot that shows this. But How to upload them here.

**Comment by raxso1** [comment] 2017-11-23 12:43
@dead8171 Hi, deleted xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership, zipped the file and  version 9.0.0.0. Although I cannot see xSQLServerSetup, I recompiled my SQL DSC config in AA and it completed successfully. Applied the config to one of my VMs and it worked. Try it out.

**Comment by mgreenegit** [comment] 2017-11-29 15:16
Version 9+ of SqlServerDsc resolve this issue.  While you will not see SqlSetup listed in the extracted activities for the module (yet), configurations that use the resource will now compile successfully.  I believe we can mark the issue as resolved?

**Comment by mattpound808** [comment] 2017-12-01 13:12
@mgreenegit I'm using version 9.0.0.0 of xSQLServer and I'm still facing the same issue with the complication job failing with the same errors.

**Comment by johlju** [comment] 2017-12-01 15:23
@mattpound808 It should be version 10.0.0.0 which has not yet been release, and will be release as SqlServerDsc. It is currently the one in the Dev branch, so you could try manually upload the dev branch until we can release the new version (soon I hope).

**Comment by johlju** [comment] 2017-12-01 15:24
@mattpound808 and please read the change log since all the resources has been renamed.

**Comment by NikCharlebois** [comment] 2017-12-08 15:10
Actually, even if I download 10.0.0.0 from GitHub, package and upload it to the gallery, I still can't use SQLSetup. The import stops at the SQLServiceAccount resource no matter what. If I remove this resource from the module, then it stops at SQLServerRole. I believe the issue is therefore in the SQLSetup resource. 

If I remove the SQLSetup from the module, then everything loads fine all the way down to SQLWindowsFirewall. So this proves that the culprit is SQLServerSetup. The issue is related to the fact that the SQLSetup resource contains culture sub-folders, which Azure Automation doesn't like. @mgreenegit any idea what may be causing this? We don't seem to have any logs on our end.

**Comment by johlju** [comment] 2017-12-08 16:56
@NikCharlebois In my tests even if you don't see the resource in the list, you are able to compile using the resource. Are you not able to compile?

**Comment by NikCharlebois** [comment] 2017-12-08 17:14
Not able. If I import from the gallery, then the compilation job complains about the Resource not found. If I remove the 2 culture folders from the SQLSetup resource, then zip and manually upload to the Modules assets in Azure Automation then it works

**Comment by johlju** [comment] 2017-12-08 18:52
1. I took the latest dev version.
2. Make sure everything was in the root of the SqlServerDsc folder
3. Zipped it.
4. Uploaded the zipped archive to the *Modules* section of Azure Automation.
5. Clicked on the imported resource module.
  ![image](https://user-images.githubusercontent.com/7189721/33780419-fd173eb4-dc50-11e7-9501-21eb6fa63620.png)
6. Compiled a simple SqlSetup configuration.
  ![image](https://user-images.githubusercontent.com/7189721/33780488-42fb5762-dc51-11e7-82f1-438c3233b423.png)

It looks okay to me. How come it doesn't work for you? 🤔

**Comment by johlju** [comment] 2017-12-08 18:56
Btw. I usually don't see all the resources but for some reason I see all now. Tried uploaded it twice and it showed all resources as it should. But even if I don't see all resources in the modules view, compiling works. 
Can just hope that a fix is rolling out for the bug that existed that made resources not show.

**Comment by NikCharlebois** [comment] 2017-12-08 19:00
Did the exact same thing. Grabbed the content from the Dev branch on GitHub, and only got 27 resources loaded: 
![image](https://user-images.githubusercontent.com/2547149/33780812-1af1705c-dc20-11e7-99d4-1aeaf3c648f2.png)

**Comment by NikCharlebois** [comment] 2017-12-08 19:00
The size (kb wise) seems to differ from yours as well

**Comment by johlju** [comment] 2017-12-09 07:45
@NikCharlebois the size difference is my bad, I took the folder from a working branch where the CHANGELOG.md and README.md had more information in it.

Tested more this morning. I took all files in the downloaded zip file from the dev version on GutHub. I did not remove any files. Did you do the same?

When uploading this to an Azure Automation which is in the location West Europe I get all 30 resources (three times in a row). When uploading this to an Azure Automation which is in the location West US 2 I get only 27 resource. But even so I am able to compile SqlSetup, even if it is not shown in the list (see second image).

Azure Automation in East US 2:
![image](https://user-images.githubusercontent.com/7189721/33793689-12a5d7f2-dcbc-11e7-9d5c-a5337ae9a0f4.png)

Able to compile a configuration with the SqlSetup resource:
![image](https://user-images.githubusercontent.com/7189721/33793713-a8f99180-dcbc-11e7-8eba-c8a53fbb0dbe.png)

**Comment by NikCharlebois** [comment] 2017-12-09 13:08
I was just thinking about the different regions issue. Glad you tested. Several people managed to replicate my exact issue when using East US. I will try with West EU later today to see.

**Comment by NikCharlebois** [comment] 2017-12-13 18:08
I can reproduce it even if I create an Azure Automation account in the West EU region. The resource doesn't show in the list (it stops at SQLServiceAcount), and my configuration don't compile. Not sure if this is caused by the blob storage it is uploaded to in the background or what. As mentioned, I managed to get it replicated by several colleagues as well. It seems like SQLServer (xSQLServer) is the only module affected at the moment.

**Comment by NikCharlebois** [comment] 2017-12-13 18:55
Any chances we could get a prereleased version (https://blogs.msdn.microsoft.com/powershell/2017/12/05/prerelease-versioning-added-to-powershellget-and-powershell-gallery/) in the gallery to make sure we are both trying out the same package and compare results. This is currently a major show stopper for many clients that used to be able to automate their full deployments via ARM and DSC.

**Comment by NikCharlebois** [comment] 2017-12-15 02:50
Folks on this thread. SQLServerDSC (v10) just got published to the gallery today. Please give it a go. The resource still doesn't show in the list of imported resources, but it seems like the configurations now compile just fine. Make sure you do use the new resources name (e.g. SQLSetup instead of xSQLServerSetup)

**Comment by johlju** [comment] 2017-12-22 13:32
Labeled this as external and closing this as this is nothing we can resolve from our end.

**Closed by johlju** 2017-12-22 13:32 UTC
Labels: external
