### ISSUE TITLE
SqlSetup - SQLSysAdminAccounts

### ISSUE THREAD

**Issue by riponbanik** [PowerShell/SqlServerDsc#1053] opened 2018-03-01 06:21 UTC
**Details of the scenario you tried and the problem that is occurring:**
SQLServer 2017 Developer Edition Installation fails. showing error that 

Missing system administrator account. To continue, provide at least one Windows account to provision as a SQL Server system administrator.

DSC Log shows as well that  it is not passing the SysAdminAccounts defined

VERBOSE: [EC2AMAZ-04IN6OB]:                            [[SqlSetup]SQLInstall] 'Master Data Services (MDS) feature not detected.'
VERBOSE: [EC2AMAZ-04IN6OB]:                            [[SqlSetup]SQLInstall] Using path 'D:\setup.exe'.
VERBOSE: [EC2AMAZ-04IN6OB]:                            [[SqlSetup]SQLInstall] Starting setup using arguments: /ACTION="Install" /INSTANCENAME="MSSQLSERVER" /FEATURES=SQL 
/QUIET="True" /IACCEPTSQLSERVERLICENSETERMS="True"

**The DSC configuration that is using the resource (as detailed as possible):**

SqlSetup SQLInstall {
        Sourcepath       =  "D:\"        
        Instancename     = $Instance
        Features         = $Features     
        SQLSysAdminAccounts = @("BUILTIN\ADMINISTRATORS")
        DependsOn           = '[WindowsFeature]NetFramework45Core'
      }        

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows Server 2016

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
Version 11.0.0.0

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
master

**Comment by johlju** [comment] 2018-03-01 14:36
I think the domain local group 'BUILTIN\Administrators' is only available on the Domain Controller. Are you installing SQL Server on a Domain Controller?

**Comment by riponbanik** [comment] 2018-03-05 02:50
@johlju no it is not domain controller specific, I have used the same with command line installation without any issue. I have also tried with Administrators but the issue remains.

**Comment by johlju** [comment] 2018-03-05 08:15
@riponbanik Ah sorry I did see that you wrote that it does get added to the argument list. Maybe the problem is that you using the parent feature name 'SQL' as the feature. The resource does not currently support the parent feature 'SQL', see issue #553.

Instead of 'SQL' use  'SQLENGINE' in the `$Features` variable  to install Database Engine.

**Comment by riponbanik** [comment] 2018-03-05 22:59
@johlju - no, it does not get added to the argument list and that is the issue. 

Starting setup using arguments: /ACTION="Install" /INSTANCENAME="MSSQLSERVER" /FEATURES=SQL
/QUIET="True" /IACCEPTSQLSERVERLICENSETERMS="True"

For SQL 2017 Developer Edition, it is SQL not SQLEngine, Installation via the following command line works,

.\setup.exe /QUIET /IACCEPTSQLSERVERLICENSETERMS /IACCEPTPYTHONLICENSETERMS /ACTION=install /FEATURES=SQL,ADVANCEDANALYTICS,SQL_INST_MPY /INSTANCENAME=MSSQLSERVER /TCPENABLED=1 /SECURITYMODE=SQL /SQLSVCACCOUNT="NT Authority\System" /SAPWD="xxx" /SQLSYSADMINACCOUNTS=BUILTIN\ADMINISTRATORS /MRCACHEDIRECTORY=c:\windows\temp

**Comment by johlju** [comment] 2018-03-06 13:26
The resource will currently only add the administrator accounts to the argument if the feature list contains `SQLENGINE` (line 1198), and then add the setup argument on line 1229.

https://github.com/PowerShell/SqlServerDsc/blob/5e7d4c8700b43efd5d577cf52feb92b343be6638/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1#L1198

https://github.com/PowerShell/SqlServerDsc/blob/5e7d4c8700b43efd5d577cf52feb92b343be6638/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1#L1229-L1232

Do you mean that you get an error if you use 'SQLENGINE' instead of 'SQL'? If so, what is the error message?

**Comment by riponbanik** [comment] 2018-03-06 22:54
@johlju sorry I should have looked at the code, it works perfectly now. Thanks a lot.

**Comment by johlju** [comment] 2018-03-07 07:24
@riponbanik No worries. Your scenario would have worked if we supported using the parent feature name 'SQL. 😄 I'm glad you got it to work. Closing this issue as it has been resolved.

**Closed by johlju** 2018-03-07 07:24 UTC
Labels: question
