### ISSUE TITLE
SqlServerDatabaseMail: Getting the error "Logon failure: the user has not been granted the requested logon type at this computer"

### ISSUE THREAD

**Issue by cosmos500** [PowerShell/SqlServerDsc#1381] opened 2019-06-25 16:55 UTC
#### Details of the scenario you tried and the problem that is occurring
sqlServerDatabaseMail Logon failure: the user has not been granted the requested logon type at this computer. I am installing and configuring SQL Server. During the install i am setting up Database mail but get security errors. The user i am installing with is in  a domain group that has admin access on the server and in SQL. The sql install all completes except the database mail.

#### Verbose logs showing the problem
Logon failure: the user has not been granted the requested logon type at this computer

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here

           SqlServerDatabaseMail 'EnableDatabaseMail'
           {
                Ensure               = 'Present'
                ServerName           = $Node.NodeName
                InstanceName         = $Node.InstanceName
                AccountName          = $Node.AccountName
                ProfileName          = $Node.ProfileName
                EmailAddress         = $Node.EmailAddress
                ReplyToAddress       = $Node.EmailAddress
                DisplayName          = $Node.MailServerName
                MailServerName       = $Node.MailServerName
                Description          = $Node.Description
                LoggingLevel         = $Node.LoggingLevel
                TcpPort              = $Node.TcpPort
                PsDscRunAsCredential = $Credential

            }

#### SQL Server edition and version the target node is running
sql 2016

#### SQL Server PowerShell modules present on the target node
Name                             Version Path                                                                                                                                         
----                             ------- ----                                                                                                                                         
xSQLServer                       9.1.0.0 C:\Program Files\WindowsPowerShell\Modules\xSQLServer\9.1.0.0\xSQLServer.psd1                                                                
MSFT_SqlAG                       0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlAG\MSFT_SqlAG.psm1                
MSFT_SqlAGDatabase               0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlAGDatabase\MSFT_SqlAGDatabase.psm1
MSFT_SqlAgentOperator            0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlAgentOperator\MSFT_SqlAgentOper...
MSFT_SqlAGListener               0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlAGListener\MSFT_SqlAGListener.psm1
MSFT_SqlAGReplica                0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlAGReplica\MSFT_SqlAGReplica.psm1  
MSFT_SqlAlias                    0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlAlias\MSFT_SqlAlias.psm1          
MSFT_SqlAlwaysOnService          0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlAlwaysOnService\MSFT_SqlAlwaysO...
MSFT_SqlDatabase                 0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlDatabase\MSFT_SqlDatabase.psm1    
MSFT_SqlDatabaseDefaultLocation  0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlDatabaseDefaultLocation\MSFT_Sq...
MSFT_SqlDatabaseOwner            0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlDatabaseOwner\MSFT_SqlDatabaseO...
MSFT_SqlDatabasePermission       0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlDatabasePermission\MSFT_SqlData...
MSFT_SqlDatabaseRecoveryModel    0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlDatabaseRecoveryModel\MSFT_SqlD...
MSFT_SqlDatabaseRole             0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlDatabaseRole\MSFT_SqlDatabaseRo...
MSFT_SqlRS                       0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlRS\MSFT_SqlRS.psm1                
MSFT_SqlRSSetup                  0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlRSSetup\MSFT_SqlRSSetup.psm1      
MSFT_SqlScript                   0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlScript\MSFT_SqlScript.psm1        
MSFT_SqlScriptQuery              0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlScriptQuery\MSFT_SqlScriptQuery...
MSFT_SqlServerConfiguration      0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServerConfiguration\MSFT_SqlSer...
MSFT_SqlServerDatabaseMail       0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServerDatabaseMail\MSFT_SqlServ...
MSFT_SqlServerEndpoint           0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServerEndpoint\MSFT_SqlServerEn...
MSFT_SqlServerEndpointPermission 0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServerEndpointPermission\MSFT_S...
MSFT_SqlServerEndpointState      0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServerEndpointState\MSFT_SqlSer...
MSFT_SqlServerLogin              0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServerLogin\MSFT_SqlServerLogin...
MSFT_SqlServerMaxDop             0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServerMaxDop\MSFT_SqlServerMaxD...
MSFT_SqlServerMemory             0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServerMemory\MSFT_SqlServerMemo...
MSFT_SqlServerNetwork            0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServerNetwork\MSFT_SqlServerNet...
MSFT_SqlServerPermission         0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServerPermission\MSFT_SqlServer...
MSFT_SqlServerReplication        0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServerReplication\MSFT_SqlServe...
MSFT_SqlServerRole               0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServerRole\MSFT_SqlServerRole.psm1
MSFT_SqlServerSecureConnection   0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServerSecureConnection\MSFT_Sql...
MSFT_SqlServiceAccount           0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlServiceAccount\MSFT_SqlServiceA...
MSFT_SqlSetup                    0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlSetup\MSFT_SqlSetup.psm1          
MSFT_SqlWaitForAG                0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlWaitForAG\MSFT_SqlWaitForAG.psm1  
MSFT_SqlWindowsFirewall          0.0     C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\SqlServerDscOLD\12.5.0.0\DSCResources\MSFT_SqlWindowsFirewall\MSFT_SqlWindows...

#### The operating system the target node is running


    Server 2016

#### Version and build of PowerShell the target node is running
5.1.14393.2969 

#### Version of the DSC module that was used ('dev' if using current dev branch)

**Comment by johlju** [comment] 2019-06-26 15:07
It must be that the user in the `PsDscRunAsCredential = $Credential` are not allowed to log on locally (in Windows, not SQL) on the node? I'm guessing the resource SqlServerDatabaseMail  does not even start? 
Can you verify in the security event log that the account name in the `$Credential` is not allowed to logon locally?

**Comment by cosmos500** [comment] 2019-06-27 12:55
Yes i added the account to the local backup operators to allow for logon privileges. Maybe you can help with this new problem. The database mail seems to complete successfully but after it is complete the database mail is not set up. Here are the logs

VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Connecting to SQL Server instance 'MyServer\MSSQLSERVER'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Information: PowerShell module SqlServer not found, trying to use older SQLPS module.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Importing PowerShell module 'SQLPS' with version '1.0' from path 'M:\Program Files (x86)\Microso
ft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Connected to SQL instance 'MyServer'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] SQL Server Database Mail is enabled. Database Mail XPs are set to 1.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Account name 'SQLMAIL' was not found.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Determines if the Database Mail is in the desired state.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] String value for property AccountName does not match. Current state is '' and desired state is '
SQLMAIL'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] String value for property EmailAddress does not match. Current state is '' and desired state is 
'Service.myservice.ab.ca'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] String value for property MailServerName does not match. Current state is '' and desired state i
s 'MyMailRelay'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] String value for property ProfileName does not match. Current state is '' and desired state is '
SQLMAIL'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] String value for property Ensure does not match. Current state is 'Absent' and desired state is 
'Present'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] String value for property ReplyToAddress does not match. Current state is '' and desired state i
s 'Service.myservice.ab.ca'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] UInt16 value for property TcpPort does not match. Current state is '' and desired state is '25'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] String value for property DisplayName does not match. Current state is '' and desired state is '
MyMailRelay'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] String value for property Description does not match. Current state is '' and desired state is '
SQL Server Database Mail'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] String value for property LoggingLevel does not match. Current state is '' and desired state is 
'Normal'.
VERBOSE: [MyServer]: LCM:  [ End    Test     ]  [[SqlServerDatabaseMail]EnableDatabaseMail]  in 3.7660 seconds.
VERBOSE: [MyServer]: LCM:  [ Start  Set      ]  [[SqlServerDatabaseMail]EnableDatabaseMail]
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Connecting to SQL Server instance 'MyServer\MSSQLSERVER'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Found PowerShell module Sqlps already imported in the session.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Connected to SQL instance 'MyServer'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Changing the SQL Server Database Mail logging level to 'Normal' (value '1').
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Creating the mail account 'SQLMAIL'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Creating a public default profile 'SQLMAIL'.
VERBOSE: [MyServer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Configure the SQL Agent to use Database Mail.
VERBOSE: [MyServer]: LCM:  [ End    Set      ]  [[SqlServerDatabaseMail]EnableDatabaseMail]  in 0.9060 seconds.
VERBOSE: [MyServer]: LCM:  [ End    Resource ]  [[SqlServerDatabaseMail]EnableDatabaseMail]

**Comment by johlju** [comment] 2019-06-27 16:02
The resource are not reporting any problem, can you see any error in the SQL server logs or event log that can give you a clue to why it didn’t work?

**Comment by cosmos500** [comment] 2019-06-27 17:06
No i do not see any errors. I assume that i should be able to see the database mail setup in the GUI

**Comment by johlju** [comment] 2019-06-27 17:18
I assume that yes. If you run the configuration again, does it say it already exist? If so it did work, and not sure why you are not seeing it in the GUI :thinking:

**Comment by cosmos500** [comment] 2019-06-27 17:50
i ran it again and it does think its there i am puzzled

vERBOSE: [MyComputer]: LCM:  [ Start  Resource ]  [[SqlServerDatabaseMail]EnableDatabaseMail]
VERBOSE: [MyComputer]: LCM:  [ Start  Test     ]  [[SqlServerDatabaseMail]EnableDatabaseMail]
VERBOSE: [MyComputer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Connecting to SQL Server instance 'MyComputer\MSSQLSERVER'.
VERBOSE: [MyComputer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Information: PowerShell module SqlServer not found, trying to use older SQLPS module.
VERBOSE: [MyComputer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Importing PowerShell module 'SQLPS' with version '1.0' from path 'M:\Program Files (x86)\Microso
ft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1'.
VERBOSE: [MyComputer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Connected to SQL instance 'MyComputer'.
VERBOSE: [MyComputer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] SQL Server Database Mail is enabled. Database Mail XPs are set to 1.
VERBOSE: [MyComputer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Account name 'SQLMAIL' was found, returning the current state of the Database Mail configuration
.
VERBOSE: [MyComputer]:                            [[SqlServerDatabaseMail]EnableDatabaseMail] Determines if the Database Mail is in the desired state.
VERBOSE: [MyComputer]: LCM:  [ End    Test     ]  [[SqlServerDatabaseMail]EnableDatabaseMail]  in 2.4120 seconds.
VERBOSE: [MyComputer]: LCM:  [ Skip   Set      ]  [[SqlServerDatabaseMail]EnableDatabaseMail]
VERBOSE: [MyComputer]: LCM:  [ End    Resource ]  [[SqlServerDatabaseMail]EnableDatabaseMail]

**Comment by johlju** [comment] 2019-06-27 17:58
Maybe there is a bug, something more that need to be configured, that makes it not show in the GUI. :thinking: Please comment here when you find out the cause.

**Comment by cosmos500** [comment] 2019-07-02 16:50
well lol i do not think it will that easy to figure out

**Comment by cosmos500** [comment] 2019-07-05 15:35
I have a question about logic. i have the script working to install the base sql. I want the option for the user to install reporting services. I have all the module info set up and it creates the info in the mof file. I want to ask the person if they want reporting services installed and they will answer yes or no. How do. How do i prevent the install of reporting services if they say no. I do not think if statement works in the config part of the script.

**Comment by johlju** [comment] 2019-07-05 16:00
A DSC configuration is the desired state you want that node to have. If another node needs another desired state then that is another configuration.  
The logic you are looking for is some another tool outside of DSC that builds the configurations. There are no interaction with the use once the configuration is compiled. The compiled configuration is the desired state. 
I suggest you ask these questions to the community in the DSC Slack channel which can provide you with more real world suggestions. See there how to join https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/2019-08-01/agenda.md

Also please open a new issue if you have questions that is not part of this issue. Since the initial question was answered I will close this issue.

**Closed** 2019-07-05 16:00 UTC
Labels: question
